name: FarmLandRpg
version: '${project.version}'
main: me.aokigahara.farmlandrpg.FarmLandRpg
api-version: '1.20'
commands:
  qtc:
    usage: "aa"
  getblaster:
    description: "Gives a blaster to the player."
  opbuilding:
    usage: "no usefe"